// 格式：{ name: "餐厅名", icon: "图标" },
window.restaurantData = [
  { name: "海底捞", icon: "🍲" },
  { name: "麦当劳", icon: "🍔" },
  { name: "塔斯汀汉堡", icon: "🍔" },
  { name: "日式烤肉", icon: "🥩" },
  { name: "萨莉亚", icon: "🍝" },
  { name: "川菜（眉州东坡）", icon: "🌶️" },
  { name: "粤菜（繁楼/点都德/小海鲜/香江）", icon: "🧋" },
  { name: "达美乐披萨", icon: "🍕" },
  { name: "拌饭（旬福食堂）", icon: "🍚" },
  { name: "太二酸菜鱼/烤鱼", icon: "🐟" },
  { name: "井梅无锡酱排骨面/沪西老弄堂/福和面馆", icon: "🍜" },
  { name: "牛new寿喜烧自助", icon: "🍻" },
  { name: "泰式咖喱/印度菜", icon: "🍛" },
  { name: "韩餐（阿吉特/李教授）", icon: "🥘" },
  { name: "江西菜", icon: "🌶️" },
  { name: "江浙沪菜（阿月煲）", icon: "🥟" },
  { name: "日料(铁板烧/烧鸟)", icon: "🍱" },
  { name: "韩式烤肉", icon: "🥩" },
  { name: "烧烤大排档/牛羊肉涮锅", icon: "🍻" },
  { name: "潮汕牛肉火锅/鸿姐老火锅/贵州酸汤火锅", icon: "🍲" },
  { name: "北京菜", icon: "🌯" },
  { name: "西餐漂亮饭", icon: "🥗" },
  { name: "很久以前羊肉串", icon: "🥩" },
  { name: "湘菜（潇湘阁）", icon: "🌶️" },
  { name: "回转寿司", icon: "🍣" }
];